/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeLibrary */

#ifndef _Included_NativeLibrary
#define _Included_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeLibrary
 * Method:    printOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeLibrary_printOne
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
